from especie import Especie
animal1 = Especie("Chimpanzé", "Animal", "Cordados", "Mamíferos", "Primata", "Hominídeos", "Pan", "troglodytes - Chimpanzé")
animal2 = Especie("Leão", "Animal", "Cordados", "Mamíferos", "Carnívora", "Felidae", "Panthera", "leo - Leão")
animal3 = Especie("Lobo", "Animal", "Cordados", "Mamíferos", "Carnívora", "Canidae", "Canis", "lupus - Lobo")
animal4 = Especie("Boi", "Animal", "Cordados", "Mamíferos", "Artiodactyla", "Bovidae", "Bos", "taurus - Boi")
animal5 = Especie("Orca", "Animal", "Cordados", "Mamíferos", "Cetacea", "Delphinidae", "Orcinus", "orca - Orca")
animal6 = Especie("Rato", "Animal", "Cordados", "Mamíferos", "Rodentia", "Muridae", "Rattus", "norvegicus - Rato")
animal7 = Especie("Águia-careca", "Animal", "Cordados", "Aves", "Falconiformes", "Accipitridae", "Haliaeetus", "leucocephalus - Águia-careca")
animal8 = Especie("Pardal", "Animal", "Cordados", "Aves", "Passeriformes", "Passeridae", "Passer", "domesticus - Pardal")
animal9 = Especie("Bufo-real", "Animal", "Cordados", "Aves", "Strigiformes", "Strigidae", "Bubo", "bubo - Bufo-real")
animal10 = Especie("Arara-canindé", "Animal", "Cordados", "Aves", "Psittaciformes", "Psittacidae", "Ara", "ararauna - Arara-canindé")
animal11 = Especie("Jararaca", "Animal", "Cordados", "Répteis", "Squamata", "Viperidae", "Bothrops", "atrox - Jararaca")
animal12 = Especie("Crocodilo-de-água-salgada", "Animal", "Cordados", "Répteis", "Crocodylia", "Crocodylidae", "Crocodylus", "porosus - Crocodilo-de-água-salgada")
animal13 = Especie("Sapo-marinho", "Animal", "Cordados", "Anfíbios", "Anura", "Bufonidae", "Rhinella", "marina - Sapo-marinho")
animal14 = Especie("Axolote", "Animal", "Cordados", "Anfíbios", "Caudata", "Salamandridae", "Ambystoma", "mexicanum - Axolote")
animal15 = Especie("Peixe-palhaço", "Animal", "Cordados", "Peixes", "Perciformes", "Pomacentridae", "Amphiprion", "ocellaris - Peixe-palhaço")
animal16 = Especie("Arowana", "Animal", "Cordados", "Peixes", "Osteoglossiformes", "Osteoglossidae", "Scleropages", "formosus - Arowana")
animal17 = Especie("Peixe-dourado", "Animal", "Cordados", "Peixes", "Cypriniformes", "Cyprinidae", "Carassius", "auratus - Peixe-dourado")
animal18 = Especie("Bagre-pintado", "Animal", "Cordados", "Peixes", "Siluriformes", "Pimelodidae", "Pimelodus", "pictus - Bagre-pintado")
animal19 = Especie("Tarântula-rosa-chilena", "Animal", "Cordados", "Aracnídeos", "Araneae", "Theraphosidae", "Grammostola", "rosea - Tarântula-rosa-chilena")
animal20 = Especie("Escorpião-preto", "Animal", "Cordados", "Aracnídeos", "Scorpiones", "Buthidae", "Androctonus", "australis - Escorpião-preto")
animal21 = Especie("Escaravelho", "Animal", "Cordados", "Insetos", "Coleoptera", "Scarabaeidae", "Scarabaeus", "laticollis - Escaravelho")
animal22 = Especie("Borboleta-monarca", "Animal", "Cordados", "Insetos", "Lepidoptera", "Nymphalidae", "Danaus", "plexippus - Borboleta-monarca")
animal23 = Especie("Abelha-europeia", "Animal", "Cordados", "Insetos", "Hymenoptera", "Apidae", "Apis", "mellifera - Abelha-europeia")
animal24 = Especie("Mosquito Aedes aegypti", "Animal", "Cordados", "Insetos", "Diptera", "Culicidae", "Aedes", "aegypti - Mosquito Aedes aegypti")
animal25 = Especie("Tritão-de-crista" , "Animal", "Cordados" , "Anfíbios" , "Caudata" , "Salamandridae" , "Triturus" , "cristatus - Tritão-de-crista")
print("***********************************************************************************************")
animal1.imprimir_dados()
print("***********************************************************************************************")
animal2.imprimir_dados()
print("***********************************************************************************************")
animal3.imprimir_dados()
print("***********************************************************************************************")
animal4.imprimir_dados()
print("***********************************************************************************************")
animal5.imprimir_dados()
print("***********************************************************************************************")
animal6.imprimir_dados()
print("***********************************************************************************************")
animal7.imprimir_dados()
print("***********************************************************************************************")
animal8.imprimir_dados()
print("***********************************************************************************************")
animal9.imprimir_dados()
print("***********************************************************************************************")
animal10.imprimir_dados()
print("***********************************************************************************************")
animal11.imprimir_dados()
print("***********************************************************************************************")
animal12.imprimir_dados()
print("***********************************************************************************************")
animal13.imprimir_dados()
print("***********************************************************************************************")
animal14.imprimir_dados()
print("***********************************************************************************************")
animal15.imprimir_dados()
print("***********************************************************************************************")
animal16.imprimir_dados()
print("***********************************************************************************************")
animal17.imprimir_dados()
print("***********************************************************************************************")
animal18.imprimir_dados()
print("***********************************************************************************************")
animal19.imprimir_dados()
print("***********************************************************************************************")
animal20.imprimir_dados() 
print("***********************************************************************************************")
animal21.imprimir_dados()
print("***********************************************************************************************")
animal22.imprimir_dados()
print("***********************************************************************************************")
animal23.imprimir_dados()
print("***********************************************************************************************")
animal24.imprimir_dados()
print("***********************************************************************************************")
animal25.imprimir_dados()
print("***********************************************************************************************")

